{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"run_code.ipynb","provenance":[],"authorship_tag":"ABX9TyPj/ddqtZQ8O8RRrZ3LAV8G"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"qvaQMRercMys","executionInfo":{"status":"ok","timestamp":1615707056512,"user_tz":-480,"elapsed":788,"user":{"displayName":"Jun Yu","photoUrl":"","userId":"03149508337013056244"}},"outputId":"d37539fa-1a18-4dc6-fb99-f73bfd732ba9"},"source":["from google.colab import drive\n","drive.mount('/content/gdrive/')"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount(\"/content/gdrive/\", force_remount=True).\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ZGGsSYFTcauy","executionInfo":{"status":"ok","timestamp":1615707057827,"user_tz":-480,"elapsed":559,"user":{"displayName":"Jun Yu","photoUrl":"","userId":"03149508337013056244"}},"outputId":"cd9c4b0b-e8bf-4583-e59b-518b9d47e809"},"source":["%cd /content/gdrive/MyDrive/CSE-498/Adversarial_Learning"],"execution_count":2,"outputs":[{"output_type":"stream","text":["/content/gdrive/MyDrive/CSE-498/Adversarial_Learning\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3BgE7XNPcw3m","executionInfo":{"status":"ok","timestamp":1615698779264,"user_tz":-480,"elapsed":881,"user":{"displayName":"Jun Yu","photoUrl":"","userId":"03149508337013056244"}},"outputId":"7edb4860-c6db-4820-d6bb-d9bcd95c9140"},"source":["!ls\n","!nvidia-smi"],"execution_count":21,"outputs":[{"output_type":"stream","text":["base_model.py\t datasets  __pycache__\trun_code.ipynb\n","data_process.py  main.py   README.md\n","NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.\n","\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"cqLvIaTGc71t","executionInfo":{"status":"ok","timestamp":1615708518685,"user_tz":-480,"elapsed":2733,"user":{"displayName":"Jun Yu","photoUrl":"","userId":"03149508337013056244"}},"outputId":"29b383a5-fe9d-486c-add0-d0917892b5a9"},"source":["!python learning_main.py"],"execution_count":14,"outputs":[{"output_type":"stream","text":["Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ./datasets/MNIST/raw/train-images-idx3-ubyte.gz\n","Traceback (most recent call last):\n","  File \"learning_main.py\", line 11, in <module>\n","    train_dset = datasets.MNIST(root='./datasets', train = True, download = True)\n","  File \"/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py\", line 79, in __init__\n","    self.download()\n","  File \"/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py\", line 146, in download\n","    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)\n","  File \"/usr/local/lib/python3.7/dist-packages/torchvision/datasets/utils.py\", line 314, in download_and_extract_archive\n","    download_url(url, download_root, filename, md5)\n","  File \"/usr/local/lib/python3.7/dist-packages/torchvision/datasets/utils.py\", line 140, in download_url\n","    raise e\n","  File \"/usr/local/lib/python3.7/dist-packages/torchvision/datasets/utils.py\", line 132, in download_url\n","    _urlretrieve(url, fpath)\n","  File \"/usr/local/lib/python3.7/dist-packages/torchvision/datasets/utils.py\", line 29, in _urlretrieve\n","    with urllib.request.urlopen(urllib.request.Request(url, headers={\"User-Agent\": USER_AGENT})) as response:\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 222, in urlopen\n","    return opener.open(url, data, timeout)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 531, in open\n","    response = meth(req, response)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 641, in http_response\n","    'http', request, response, code, msg, hdrs)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 569, in error\n","    return self._call_chain(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n","    result = func(*args)\n","  File \"/usr/lib/python3.7/urllib/request.py\", line 649, in http_error_default\n","    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n","urllib.error.HTTPError: HTTP Error 503: Service Unavailable\n"],"name":"stdout"}]}]}